### PR TITLE
Run Clippy as GitHub action

### PR DESCRIPTION
**Pull request by heeckhau**
#24

### CODE REVIEW

**Review by sinui0 — APPROVED** [review]

**Comment by heeckhau** [comment]
@sinui0 merging this would break the build. (https://github.com/tlsnotary/mpz/actions/runs/5311883601/jobs/9615674331?pr=25):
```
| error[E0554]: `#![feature]` may not be used on the stable release channel
```

**Comment by sinui0** [comment]
Can we temporarily exclude this crate from the clippy invocation?

**Comment by heeckhau** [comment]
@sinui0 it works when we use nightly

**Comment by sinui0** [comment]
:+1:

**Pull request merged**
